language: ruby
rvm:
- 2.4
- 2.5
- 2.6
sudo: false
cache: bundler
before_script: bundle update
notifications:
  slack:
    rooms:
      secure: b/9R2CQSsanEWhd52ku+fTliEyoQooPdRtsrABWW+mGetLLWAk+jzZaOwpbvtMfdB67iReMMubdfy7akmq/khxqP00QNy/pOkJWojsNeXWADVZmaAzJFcMsTN3egWDatRYufuZcwTisWErMF63PMKSJk3CETEJ2zrxiNu7bbQOjEaeKA78cZLVQQ0u6g3xYOL4unNCdDsRreaRHqC0PJz8OKLPgpGNqfPOauZpYF3Opv1k3NwwC5nWQNpKZfHeW/sQeHnkxDKXn+29HJhujYrZs7owXVGLf21QPZxn5wN7ng5R49GUs+twL7oa/ovhFQ1+OpvSw0vku/4MDA3V50FTQ1nqTebFEVKE+FhAWQz0fc+Hlf4Dw+iVBAMNzFJ6m/2IG3X1YSSz20QrKeEbuhZbfkHM1U/t2HOcy3zuELPwnek27j8V3zgU7+0AMoIKibnW0aKQTZEw6MV6UNmEkBAYiDfT17A1Qol58aJIh2lKsWS+6qSAcGVo8P0zuv81k9PPKxp+QQPYDpi77cPUiTT2GNqAh0b84UXDhfrHmdBMDreRAPUTTqUxuHyQ7fsuTQ+RL7il4LjbiREOHvPvt1X5Nq9wehGIofjtCNzbYEV1UfzXuB0X4EUXioy/QoOPa/FExQ8XYZggIgefQRi0qi9UFZprHGEmzXSj+9kV798Qo=
