name: Test

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        ruby-version:
          - 2.6
          - 2.7
          - 3.0
        gemfile:
          - gemfiles/Gemfile.rails52
          - gemfiles/Gemfile.rails60

    runs-on: ubuntu-latest

    env:
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
    - name: Install dependencies
      run: bundle install
    - name: Run tests
      run: bundle exec rake

  notify:
    # Run only on master, but regardless of whether tests past:
    if: ${{ always() && github.ref == 'refs/heads/master' }}

    needs: test

    runs-on: ubuntu-latest

    steps:
    - uses: 8398a7/action-slack@v3
      with:
        status: custom
        fields: workflow,commit,author
        custom_payload: |
          {
            channel: 'C7FQWGDHP',
            username: 'CI – ' + '${{ github.repository }}'.split('/')[1],
            icon_emoji: ':hammer_and_wrench:',
            attachments: [{
              color: '${{ needs.test.result }}' === 'success' ? 'good' : '${{ needs.test.result }}' === 'failure' ? 'danger' : 'warning',
              text: `${process.env.AS_WORKFLOW} against \`${{ github.ref }}\` (${process.env.AS_COMMIT}) for ${{ github.actor }} resulted in *${{ needs.test.result }}*.`
            }]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
